#!/bin/bash -l

## configuration

set -eo pipefail

# shellcheck disable=SC1091
source "$HOME/.bashrc" || exit 1

if [[ $LOG_LEVEL == "TRACE" ]]
then 
    set -x
fi

## preflight

if [[ ! $WORKSPACE ]]
then
    declare WORKSPACE
    WORKSPACE=$(git rev-parse --show-toplevel)
    export WORKSPACE
    printf "INFO: WORKSPACE %s\n" "${WORKSPACE}"
fi

# shellcheck disable=SC1091
source "${WORKSPACE}/.tmp/toolchain-management/libs/bash/git/common.sh"

# Toolchain autoUpdate
if [[ "${WL_GC_TOOLCHAIN_UPDATE_OVERRIDE}" != "" ]]
then 
    printf "WARN: Toolchain Management automatic updates disabled.\n"
else
    autoUpdate
fi

# rebaseFromOriginMain

# Logic

declare DIFF_LOGIC
DIFF_LOGIC="git diff HEAD --name-only"
printf "INFO: DIFF_LOGIC %s\n" "${DIFF_LOGIC}"

# Next version of the feature add (> 0.64.0)
# declare DIFF_LIST
# DIFF_LIST=$(generateDiffList "${DIFF_LOGIC}")
# if [[ ! ${DIFF_LIST} ]]
# then
#     printf "WARN: IAC DIFF_LIST is empty, exiting without error.\n"
#     exit 0
# fi
# printf "INFO: DIFF_LIST: %s\n" "${DIFF_LIST}"

# execute "${DIFF_LIST}"

printf "INFO: Git hook completed successfully.\n"
