#!/bin/bash -l

# set -exo pipefail # when debuggin
set -eo pipefail

# shellcheck disable=SC1091
source "$HOME/.bashrc" || exit 1

if [[ $LOG_LEVEL == "TRACE" ]]
then 
    set -x
fi

## Logic

if [[ ! $WORKSPACE ]]
then
    declare WORKSPACE
    WORKSPACE=$(git rev-parse --show-toplevel)
    export WORKSPACE
    printf "INFO: WORKSPACE %s\n" "${WORKSPACE}"
fi

# Toolchain autoUpdate
if [[ "${WL_GC_TOOLCHAIN_UPDATE_OVERRIDE}" != "" ]]
then 
    printf "WARN: Toolchain Management automatic updates disabled.\n"
else
    autoUpdate
fi

# Logic

declare DIFF_LOGIC
DIFF_LOGIC="git diff HEAD --name-only"
printf "INFO: DIFF_LOGIC %s\n" "${DIFF_LOGIC}"

declare DIFF_LIST
DIFF_LIST=$(generateDiffList "${DIFF_LOGIC}")
if [[ ! ${DIFF_LIST} ]]
then
    printf "WARN: IAC DIFF_LIST is empty, exiting without error.\n"
    exit 0
fi
printf "INFO: DIFF_LIST: %s\n" "${DIFF_LIST}"

exec ${DIFF_LIST}

printf "INFO: Git pre-commit hook completed successfully.\n"
